### ISSUE TITLE
Teams page gets data from API, does not render table

### ISSUE THREAD

**Issue by DeBraid** [DeBraid/puck#11]
When attempting to load anything > 2 years results in empty table.

JSON appears in the console, something up with `ng-repeat`er in the `team_data_table` perhaps?  But data is in the network panel, makes it into the Teams Controller. .... 

To reproduce, visit: http://puckalytics.com/puck-master/#/teams?season=201216

Then http://puckalytics.com/puck-master/#/teams?season=201416

Note that `season=201416` works, but anything after '14 will not, ie `season=201216`.

**Comment by David-W-Johnson** [comment]
Some of the default max filters were too restrictive for 4+ seasons of data. Teams were getting filtered out for having CF and CA over the default max. Increased the defaults. Should work now.
